spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memora_db #local, for tests
    username: memora_user
    password: memora_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
